name: "SOOS DAST Scan"

on:
  workflow_run:
    workflows: ["Deply"]
    types:
      - completed
    branches: [ "main" ]

jobs:
  soos:
    permissions:
      security-events: write # for uploading code scanning alert info
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: SOOS DAST Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
    
      - name: Download Deployment URL Artifact
        uses: actions/download-artifact@v2
        with:
          name: deployment-url # Name of the artifact
    
      - name: Read Deployment URL
        id: read-url
        run: echo "DEPLOYMENT_URL=$(cat deployment-url)" >> $GITHUB_ENV
    
      - name: Run SOOS DAST Scan
        uses: soos-io/soos-dast-github-action@3e71b27756f4ed77d7ad3c0ad92afddb47a40e4d
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: "dast scanned"
          scan_mode: "baseline"
          target_url: ${{ env.DEPLOYMENT_URL }}
          output_format: "sarif"
      - name: Upload SOOS DAST SARIF Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

  IAST:
    name: IAST Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v2
        
      - name: Build with Maven 
        run: mvn -B package --file app/pom.xml
          
      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: 'VeraDemo'
          createprofile: false
          filepath: 'app/target/verademo.war'
          vid: '${{ secrets.API_ID }}'
          vkey: '${{ secrets.API_KEY }}'